StaffWeb/Controllers/ForgotPasswordController.cs
using System;
using System.Linq;
using System.Net;
using System.Net.Mail;
using BLL;
using DAL.Context;
using Microsoft.AspNetCore.Mvc;
using Model;

namespace StaffWeb.Controllers
{
    public class ForgotPasswordController : Controller
    {
        private IUserNameService UsernameService;
        public EmailModel emailmodel;

        private readonly KtMPracticeContext Context;

        public ForgotPasswordController(IUserNameService uService, KtMPracticeContext context)
        {
            UsernameService = uService;
            Context = context;
        }
        public IActionResult Index()
        {
            return View("~/Views/ForgotPassword/ForgotPassword.cshtml");
            //return View();   
        }




        public IActionResult Resetpassword(string username, string accesscode = null, string expiredate = null)
        {
            
            if (ModelState.IsValid)
            {
                bool valid;

                valid = UsernameService.ValidateUser(username);


                if (valid)
                {
                    // return RedirectToAction("ResetPassword", "ForgotPassword");
                    // write a code for generating a email link
                    if (!string.IsNullOrEmpty(accesscode))
                    {

                        byte[] data = Convert.FromBase64String(expiredate);
                        string exceedata = System.Text.ASCIIEncoding.ASCII.GetString(data);
                        if (Convert.ToDateTime(exceedata).AddMinutes(2) >= DateTime.Now)
                        {
                            // bool AccessChecker = UsernameService.AccessChecker(username, accesscode);
                            var accesschecker = Context.Logins.Where(x => x.Username == username);
                            if (accesschecker.FirstOrDefault().accesscode != accesscode)
                            {
                                TempData["message"] = "Your can not modify the url name";
                                return RedirectToAction("login", "login");

                            }

                            return View();
                        }
                        else
                        {
                            TempData["message"] = "Your token time is expired";
                            return RedirectToAction("login", "login", TempData["message"]);
                        }


                    }
                    else
                    {
                        string resetCode = Guid.NewGuid().ToString();
                        bool AccessCode2 = UsernameService.AccessCode2(username,resetCode );
                        
                        byte[] datetime = System.Text.Encoding.UTF8.GetBytes(DateTime.Now.ToString());


                        var verifyUrl = "/ForgotPassword/ResetPassword?accesscode=" + resetCode;
                        var link = "https://" + Request.Host.Value + verifyUrl + "&&username=" + username + "&&expiredate=" + System.Convert.ToBase64String(datetime);


                        var Subject = "Password Reset Request";
                        var body = "Hi " + username + ", <br/> You recently requested to reset your password for your account. Click the link below to reset it. " +

                             " <br/><br/><a href='" + link + "'>" + link + "</a> <br/><br/>" +
                             "If you did not request a password reset, please ignore this email or reply to let us know.<br/><br/> Thank you";



                        TempData["message"] = "Reset password link has been sent to your email id.";
                        SendEmail(body, Subject, username);
                        return RedirectToAction("login", "login", TempData["message"]);
                    }
                    // return View("~/Views/login/login.cshtml");
                    //return View("~/Views/ForgotPassword/ResetPassword.cshtml",username);

                }
                else
                {
                    //TempData["msg"] = "Please enter your correct username";
                    //return RedirectToAction("login", "login");
                    return View("~/Views/ForgotPassword/UpdatePassword.cshtml");


                }

            }
            //return View("~/Views/ForgotPassword/ForgotPassword.cshtml");
            return View("~/Views/login/login.cshtml");
        }



        public void SendEmail(string body, string subject, string username)
        {
            using (MailMessage mm = new MailMessage("abhiseksunar11@gmail.com", username))
            {
                mm.Subject = subject;
                mm.Body = body;
                mm.IsBodyHtml = true;
                using (SmtpClient smtp = new SmtpClient())
                {
                    System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;
                    smtp.Host = "smtp.gmail.com";
                    smtp.EnableSsl = true;
                    NetworkCredential NetworkCred = new NetworkCredential("abhiseksunar11@gmail.com", "czwualygaiytzrow");
                    smtp.UseDefaultCredentials = false;
                    smtp.Credentials = NetworkCred;
                    smtp.Port = 587;
                    smtp.Send(mm);
                    // ViewBag.Message = "Email sent.";
                }
            }

        }



        public IActionResult UpdatePassword(string username, string password, string repassword)
        {
            if (ModelState.IsValid)
            {
                if (password == repassword)
                {

                    bool valid = UsernameService.ValidateUser(username);
                    if (valid)
                    {
                        bool isUpdate = UsernameService.ResetPassword(username, password);

                        bool AccessCode= UsernameService.AccessCode( username);

                       // //string checkdata=null;
                       // var data12 = _Context.Logins.Where(x => x.Username == username).FirstOrDefault();
                       // data12.accesscode = null;
                       //// data12.isreset = "n";
                       // _Context.Logins.Update(data12);
                       // _Context.SaveChanges();
                    }
                    else
                    {
                        return View();
                    }
                }
                else
                {
                    TempData["message"] = "Your Password and Confirm Password is not match!!!!";
                    return View("~/Views/ForgotPassword/UpdatePassword.cshtml", TempData["message"]);
                }
            }

            return View("~/Views/Home/Index.cshtml");


        }

        //public IActionResult PartialView(string username)
        //{
        //    return PartialView();
        //}


    }


}

StaffWeb/Views/ForgotPassword/ForgotPassword.cshtml
@model string;
@{
}
@{
    ViewBag.Title = "Forgot Password";
}

<!DOCTYPE html>
<html>
	<head>
	<title></title>
</head>
 
<body>
	<div id="PlaceHolderHere"></div>
<h2>Forgot Password</h2>


 

	@*@using (Html.BeginForm("Forgotpassword","ForgotPassword",FormMethod.Post,new{@id="Form1"}))*@
	<form id="Form1" action="ResetPassword" method="post">
    <div class="form-horizontal">
        <hr />
        <div class="text-success">
            @TempData["msg"]
        </div>

				
				<div class="form-group">
            <label class="control-label col-md-2">Email</label>
          
		   <input class="form-control" id="Username" name="Username" type="text"  required>

		   
        </div>
		
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Reset Password" class="btn btn-success" onclick="submit() " data-toggle="ajax-modal"/>
				@*<input type="button" class="btn btn-primary" data-toggle="ajax-modal" data-target="#Reset" data-url="@Url.Action("Resetpassword")>Reset Password</button>*@
"
            </div>
        </div>
    </div>
	</form>



	

	@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>




	@*<script type="text/javascript">
    function submit() {
        var data = $("#Reset").serialize();
        console.log(data);
        alert(data);
        $.ajax({
            type: 'POST',
            url: 'https://localhost:44366/ForgotPassword/Index',
            contentType: 'application/x-www-form-urlencoded; charset=UTF-8', // when we use .serialize() this generates the data in query string format. this needs the default contentType (default content type is: contentType: 'application/x-www-form-urlencoded; charset=UTF-8') so it is optional, you can remove it
            data: data,
            success: function (Resetpassword) {
                alert('Successfully received Data ');
                console.log(result);
            },
            error: function () {
                alert('Failed to receive the Data');
                console.log('Failed ');
            }
        })
    }

</script>*@
<script>

$(function (){
	var PlaceHolderHere=$('#PlaceHolderHere')
	$('button[data-toggle="ajax-modal"]').click(function (event){
		var url = $ (this).data('url');
		$.get(url).done(funtion(data)){
			PlaceHolderElement.html(data);
			PlaceHolderElement.find('.modal').modal("show");

		}
	})
})

</script>

 <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script type="text/javascript">
        $("body").on("submit", "#Form1", function () {
            return confirm("Do you want to submit?");
        });
    </script>
    @if (ViewBag.Message != null)
    {
        <script type="text/javascript">
            window.onload = function () {
                alert('@ViewBag.Message');
            };
        </script>
    }





</body>
</html>

StaffWeb/Views/ForgotPassword/PartialView.cshtml
@model Model.login


<div class="modal fade " id="Reset">
	<div class="modal-dialog">
		<div class=" model-content">


			<div class="modal-header">
				<h4 class="modal-tittle" id="Reset">Reset</h4>
				<button type="button" class="btn btn-primary" data-dismiss="modal">
					<span>X</span>
				</button>

				<div class="modal-footer">
					<button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
					<button type="button" class="btn btn-primary" data-save="modal">Save</button>
				</div>
				
			</div>
		</div>
	</div>
</div>

StaffWeb/Views/ForgotPassword/ResetPassword.cshtml
@model string
@{
}
@{
    ViewBag.Title = "Forgot Password";
	var username=Model;
}
 
<h2>Reset Password</h2>

	<form action="/ForgotPassword/UpdatePassword" method="post">
    <div class="form-horizontal">
        <hr />
        <div class="text-success">
            @ViewBag.Message
        </div>

				
				<div class="form-group">
            <label class="control-label col-md-5">New Password  </label>
     
		   @Html.Hidden("Username",username)
		    <input class="form-control" id="Password" name="Password" type="password" placeholder="Please type a new password !!!" required>
			<label class="control-label col-md-5">Confirm Password  </label>

			<input class="form-control" id="repassword" name="repassword" type="password" placeholder="Please Confirm your password !!!" required>
		  
        </div>
		
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="btn btn-success" />


				




				@*@Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword,htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.HiddenFor(a => a.resetCode)
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
@section Scripts{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

*@










				

            </div>
        </div>
    </div>
	</form>

StaffWeb/Views/ForgotPassword/UpdatePassword.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@{
    ViewBag.Title = "Forgot Password";
}
 
<h4>last Update page</h4>
<br />
<br />

@TempData["message"]


 


	